name: globaltalk

services:
  db:
    image: postgres:${PGMAJOR:-18}
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=globaltalk
      - POSTGRES_PASSWORD=globaltalk
    ports:
      - ${DB_PORT:-54329}:5432
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  smtp:
    image: rnwood/smtp4dev:v3
    ports:
      - 2509:80

  app:
    build:
      context: "."
      dockerfile: dev.Dockerfile
      args:
        pgmajor: ${PGMAJOR:-18}
    command: ["bin/dev"]
    environment:
      - BINDING=0.0.0.0
      - DATABASE_HOST=db
      - DATABASE_NAME=globaltalk
      - DATABASE_PASSWORD=globaltalk
      - DATABASE_USERNAME=globaltalk
      - ENCRYPTION_DETERMINISTIC_KEY=utPgIi0VyKKTSbsLDUgCf5FEYaaZ5oFOo3VIGiRP61D6HcmJ
      - ENCRYPTION_KEY_DERIVATION_SALT=aTt1OMGrYJsLy81DHnU6jWkaiwfWB021mCc8ykZORFhswEio
      - ENCRYPTION_PRIMARY_KEY=XW4PCqn8xLOv533KLG2rvL4wwsctKUTsQGLsFKK3eZwqZubX
      - SMTP_SERVER=smtp
    env_file:
      - .private.env
    ports:
      - ${PORT:-5009}:3000
    volumes:
      - .:/opt/app
      - bundler:/usr/local/bundle
      - app_tmp:/opt/app/tmp
    depends_on:
      db:
        condition: service_healthy
      smtp:
        condition: service_started

volumes:
  app_tmp:
  bundler:
  pg_data:
