# Wrapper for the BIND utility `nsupdate` to send zone updates to a nameserver.
#
# Zone updates are typically secured with TSIG: Transaction Signatures.
# The server generates a key that's shared with clients that will send updates and
# those are used to sign the update requests.
#
# Example usage:
#   NSUpdate.new("example.com", server: "ns1.example.org")
#     .with_tsig_keyfile("secret.key")
#     .with_commands(send: true) do |cmd|
#       cmd.add_a("myhost1", "203.0.113.4")
#       cmd.add_a("myhost1", "203.0.113.5")
#       cmd.set_a("myhost2", "203.0.113.7")
#     end
class NSUpdate
  Error = Class.new(StandardError)

  # Transaction signatures secure the update. The server produces the secret.
  class TSIG
    class Secret
      HMAC = Enum.define_from_values("md5", "sha1", "sha224", "sha256", "sha384", "sha512")

      attr_reader :key_name, :secret, :hmac

      def initialize(key_name: nil, secret: nil, hmac: HMAC::MD5)
        @key_name = key_name
        @secret = secret
        @hmac = hmac
      end

      def to_args
        ["-y", "hmac-#{hmac}:#{key_name}:#{secret}"]
      end
    end

    class KeyFile
      attr_reader :path

      def initialize(path)
        @path = case path
        in String => s
          s
        in Pathname => path
          path.to_s
        end
      end

      def to_args
        ["-k", path]
      end
    end
  end

  class CommandSet
    attr_reader :zone, :default_ttl

    # @param zone [String] Zone name e.g. myzone.domain.com
    # @param server [String]
    #   Address of the nameserver to update.
    #   If no server is specified, nsupdate will look-up the default nameserver
    # @param default_ttl [Integer] For commands/records requiring a TTL, sets the default
    def initialize(zone, server: nil, default_ttl: 3600)
      @zone = zone.chomp(".")
      @commands = []
      @default_ttl = default_ttl

      push("server #{server}") if server
      push("zone #{zone}.")
    end

    def delete_a(name)
      push("update delete #{fqdn(name)} A")
      self
    end

    def add_a(name, ip, ttl: default_ttl)
      ip = ip_object(ip)

      unless ip.ipv4?
        raise ArgumentError, "Not an IPv4 address"
      end

      push("update add #{fqdn(name)} #{ttl} A #{ip}")
      self
    end

    # Set the one and only IPv4 address for the given hostname.
    # Deletes any existing A records and then creates a single one.
    def set_a(name, ...)
      delete_a(name).add_a(name, ...)
    end

    def to_s
      # Without `send`, the update won't actually be submitted.
      # The docs say the trailing newline *should* have the same effect as `send`,
      # but that seems to not be the case? Always include it just in case.
      [*commands, "send"].join("\n") + "\n"
    end

    private

    attr_reader :commands

    def ip_object(ip)
      case ip
      in IPAddr => obj
        obj
      in String => str
        IPAddr.new(str)
      end
    end

    def push(line)
      commands.push(line)
    end

    def fqdn(name)
      "#{name}.#{zone}."
    end
  end

  attr_reader :zone, :server, :tsig

  def initialize(zone, server: nil)
    @zone = zone
    @server = server
    @tsig = nil
    @command_set = command_set
    @logger = Rails.logger.tagged(self.class.name)
  end

  def with_tsig_secret(...)
    @tsig = TSIG::Secret.new(...)
    self
  end

  # Path to a keyfile that was generated by the server using one of:
  #   `ddns-confgen`
  #   `dnssec-keygen`
  #   `tsig-keygen`
  def with_tsig_keyfile(path)
    @tsig = TSIG::KeyFile.new(path)
    self
  end

  # @param send [Boolean] If true send commands immediately and return the result
  def with_commands(send: false)
    @command_set = CommandSet.new(zone, server:)
    yield command_set
    if send
      self.send
    else
      self
    end
  end

  def send
    send_update(command_set.to_s)
  end

  private

  attr_reader :logger, :command_set

  def send_update(body)
    args = ["-v"]

    if tsig
      args += tsig.to_args
    end

    exe = "nsupdate"

    logger.debug(exe + " " + args.join(" "))
    logger.debug(body)

    combined_output, status = Open3.capture2e(exe, *args, stdin_data: body)

    if status.success?
      logger.debug(combined_output) if combined_output.present?
      return true
    end

    raise Error, combined_output
  end
end
