default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= AppConfig.rails_max_threads! %>
  host: <%= AppConfig.database_host %>
  username: <%= AppConfig.database_username %>
  password: <%= AppConfig.database_password %>

development:
  <<: *default
  database: globaltalk_development

test:
  <<: *default
  database: globaltalk_test

production:
  primary: &primary_production
    <<: *default
    database: globaltalk_production
  cache:
    <<: *primary_production
    database: globaltalk_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: globaltalk_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: globaltalk_production_cable
    migrations_paths: db/cable_migrate
